### ISSUE TITLE
cant open numbers tab and wildlife tab

### ISSUE THREAD

**Issue by Lc2ccccc** [Mehni/kNumbers#78] opened 2024-05-26 23:29 UTC
Root level exception in OnGUI(): System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingMethodException: !!1 Verse.GenCollection.TryGetValue<!0,!1>(System.Collections.Generic.IReadOnlyDictionary`2<!!0, !!1>,!!0,!!1)at RimWorld.StatWorker.GetValue (RimWorld.StatRequest req, System.Boolean applyPostProcess) [0x00043] in <cd7169108ea74757aa50c5b33d275c15>:0at (wrapper dynamic-method) RimWorld.StatWorker.RimWorld.StatWorker.GetValue_Patch1(RimWorld.StatWorker,Verse.Thing,bool,int)at (wrapper dynamic-method) RimWorld.StatExtension.RimWorld.StatExtension.GetStatValue_Patch3(Verse.Thing,RimWorld.StatDef,bool,int)at RimWorld.StatsReportUtility+<StatsToDraw>d__26.MoveNext () [0x00128] in <cd7169108ea74757aa50c5b33d275c15>:0at System.Linq.Enumerable+ConcatIterator`1[TSource].MoveNext () [0x0002b] in <351e49e2a5bf4fd6beabb458ce2255f3>:0at System.Linq.Enumerable+WhereSelectEnumerableIterator`2[TSource,TResult].ToArray () [0x0003e] in <351e49e2a5bf4fd6beabb458ce2255f3>:0at System.Linq.Buffer`1[TElement]..ctor (System.Collections.Generic.IEnumerable`1[T] source) [0x0000a] in <351e49e2a5bf4fd6beabb458ce2255f3>:0at System.Linq.OrderedEnumerable`1[TElement].ToList () [0x00000] in <351e49e2a5bf4fd6beabb458ce2255f3>:0at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0001f] in <351e49e2a5bf4fd6beabb458ce2255f3>:0at Numbers.MainTabWindow_Numbers.GetHumanLikeStatDefs () [0x00150] in <2472b8688d25407c9e0f7210151910f3>:0at Numbers.MainTabWindow_Numbers..ctor () [0x00096] in <2472b8688d25407c9e0f7210151910f3>:0at (wrapper managed-to-native) System.Reflection.MonoCMethod.InternalInvoke(System.Reflection.MonoCMethod,object,object[],System.Exception&)at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00002] in <eae584ce26bc40229c1b1aa476bfa589>:0--- End of inner exception stack trace ---at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00014] in <eae584ce26bc40229c1b1aa476bfa589>:0at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic) [0x000a8] in <eae584ce26bc40229c1b1aa476bfa589>:0at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x00009] in <eae584ce26bc40229c1b1aa476bfa589>:0at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x00027] in <eae584ce26bc40229c1b1aa476bfa589>:0at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) [0x00020] in <eae584ce26bc40229c1b1aa476bfa589>:0at (wrapper dynamic-method) System.Activator.System.Activator.CreateInstance_Patch1(System.Type)at RimWorld.MainButtonDef.get_TabWindow () [0x00016] in <cd7169108ea74757aa50c5b33d275c15>:0at (wrapper dynamic-method) RimWorld.MainTabsRoot.RimWorld.MainTabsRoot.ToggleTab_Patch2(RimWorld.MainTabsRoot,RimWorld.MainButtonDef,bool)at RimWorld.MainButtonWorker_ToggleTab.Activate () [0x00005] in <cd7169108ea74757aa50c5b33d275c15>:0at RimWorld.MainButtonWorker.InterfaceTryActivate () [0x0008d] in <cd7169108ea74757aa50c5b33d275c15>:0at (wrapper dynamic-method) RimWorld.MainButtonWorker.RimWorld.MainButtonWorker.DoButton_Patch0(RimWorld.MainButtonWorker,UnityEngine.Rect)at RimWorld.MainButtonsRoot.DoButtons () [0x00119] in <cd7169108ea74757aa50c5b33d275c15>:0at (wrapper dynamic-method) RimWorld.MainButtonsRoot.RimWorld.MainButtonsRoot.MainButtonsOnGUI_Patch1(RimWorld.MainButtonsRoot)at (wrapper dynamic-method) RimWorld.UIRoot_Play.RimWorld.UIRoot_Play.UIRootOnGUI_Patch2(RimWorld.UIRoot_Play)at (wrapper dynamic-method) Verse.Root.Verse.Root.OnGUI_Patch2(Verse.Root)UnityEngine.StackTraceUtility:ExtractStackTrace ()(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch5 (string)(wrapper dynamic-method) Verse.Root:Verse.Root.OnGUI_Patch2 (Verse.Root)

**Comment by Mehni** [comment] 2024-05-27 04:58
Dupe of #76

 I'll need a full log which includes a list of patched methods if you want any indication of where it breaks. Most likely, you're running some mod which hasn't been fully updated.

**Comment by Lc2ccccc** [comment] 2024-05-29 19:07
i found it , i deleted  the "virtual framework" mod , now numbers its working

**Closed** 2024-07-07 18:58 UTC
